[alembic]
script_location = alembic
version_locations = %(script_location)s/versions

sqlalchemy.url = postgresql+asyncpg://postgres:postgres@localhost:5432/celery_db

[post_write_hooks]
hooks = black
black.type = python